import "@/styles/globals.css";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
const session=await getServerSession();
console.log("session is",session?.user.email)
  return (
    <html lang="en" className="container mx-auto ">
      <body>
        {children}
        <Toaster />
       
      </body>
    </html>
  );
}
